# Numpy

## Array

In [1]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])

In [ ]:
arr1

In [ ]:
arr2=np.array([1,2,3,'FBS',4,5])

In [ ]:
arr2

In [ ]:
arr1.dtype

In [ ]:
arr2.dtype

# Vectorization

## Opeartion performrd on each element of array

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])

In [ ]:
arr3=arr1+arr2
arr3

In [ ]:
arr1=arr1*10

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr2//2

In [ ]:
%%time
list1=[x for x in range(1,1001)]
list2=[x for x in range(2001,3001)]
list3=[]
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])


In [ ]:
%%time
a1=np.array([x for x in range(1,1001)])
a2=np.array([x for x in range(2001,3001)])
a3=a1+a2

In [ ]:
import sys
list1=[23,45,67,89]
sys.getsizeof(list[0])*len(list1)

In [ ]:
arr1=np.array([23,45,67,89])
arr1.itemsize*arr1.size

## Multidimentional Array

In [2]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr1.ndim

2

In [4]:
arr1.shape

(2, 4)

In [5]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr1=np.array([[[1,2],
               [3,4]],
              
                [[5,6],
                 [7,8]]])

In [7]:
arr1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
arr1.shape

(2, 2, 2)

In [9]:
arr2=np.array([[[10,20,30],
                [45,67,89],
                [20,30,70]],
               
                [[1,2,3],
                [4,5,6],
                [7,8,9]]])


In [10]:
arr2

array([[[10, 20, 30],
        [45, 67, 89],
        [20, 30, 70]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [11]:
arr2.shape

(2, 3, 3)

In [12]:
arr1.ndim

3

## Broadcasting

In [13]:
arr1=np.array([[10,20,40,50],
              [50,60,70,80]])
arr2=np.array([1,2,3,4])

In [14]:
arr3=arr1+arr2
arr3

array([[11, 22, 43, 54],
       [51, 62, 73, 84]])

In [15]:
arr1=np.array([1,2,3,4,5,6,7])
arr2=np.array([1,2,3])

In [16]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (7,) (3,) 

In [17]:
arr2=np.pad(arr2,(0,4))

In [18]:
arr2

array([1, 2, 3, 0, 0, 0, 0])

In [19]:
arr3=arr1+arr2

In [20]:
arr3

array([2, 4, 6, 4, 5, 6, 7])

## Different ways to create Array

In [21]:
l1=[18,45,67]
arr1=np.array(l1)

In [22]:
arr1

array([18, 45, 67])

In [23]:
t1=(1,2,3)
arr1=np.array(t1)
arr1

array([1, 2, 3])

In [24]:
arr1.dtype

dtype('int64')

In [25]:
s1={1,2,3}
arr1=np.array(s1)
arr1

array({1, 2, 3}, dtype=object)

In [26]:
arr1.size

1

In [27]:
arr1.shape

()

### arange()

In [28]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr2=np.arange(1,50,5)
arr2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

### random.randint()

In [30]:
arr3=np.random.randint(1,50,5)
arr3

array([45,  9,  2,  7,  6], dtype=int32)

### linspace()

In [31]:
arr4=np.linspace(1,10,25) # linearly sepaarte numbers in given range
arr4

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

### random.rand()

In [32]:
arr5=np.random.rand(10)
arr5

array([0.61463131, 0.70858219, 0.96849102, 0.26044714, 0.88666183,
       0.71113442, 0.39160464, 0.36555402, 0.89929378, 0.83537366])

### zeros()

In [33]:
arr6=np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

### ones()

In [34]:
arr7=np.ones(5)
arr7

array([1., 1., 1., 1., 1.])

### eye()

In [35]:
arr8=np.eye(4)
arr8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Different Functions

In [36]:
arr1=np.random.randint(1,50,25)

In [37]:
arr1

array([22,  8, 31, 13, 34, 17, 37,  8, 21, 17, 27, 19, 22, 30,  9, 26,  3,
       40, 32,  4, 19, 19,  6, 44, 19], dtype=int32)

In [38]:
arr1=arr1.reshape(5,5)

In [39]:
arr1

array([[22,  8, 31, 13, 34],
       [17, 37,  8, 21, 17],
       [27, 19, 22, 30,  9],
       [26,  3, 40, 32,  4],
       [19, 19,  6, 44, 19]], dtype=int32)

In [40]:
arr2=np.random.randint(1,100,10)

In [41]:
arr2

array([ 7, 39, 42, 27, 12, 99, 67, 71, 19, 66], dtype=int32)

In [42]:
arr2.min()

np.int32(7)

In [43]:
arr2.max()

np.int32(99)

In [44]:
arr2.mean()

np.float64(44.9)

In [45]:
arr2.sum()

np.int64(449)

In [46]:
arr2.argmax()

np.int64(5)

In [47]:
arr1

array([[22,  8, 31, 13, 34],
       [17, 37,  8, 21, 17],
       [27, 19, 22, 30,  9],
       [26,  3, 40, 32,  4],
       [19, 19,  6, 44, 19]], dtype=int32)

In [48]:
arr1.min(axis=0)
#axis=0: column
#axis=1:row

array([17,  3,  6, 13,  4], dtype=int32)

## Selection

In [49]:
arr2

array([ 7, 39, 42, 27, 12, 99, 67, 71, 19, 66], dtype=int32)

In [50]:
arr2[5]

np.int32(99)

In [51]:
arr2[0:2]

array([ 7, 39], dtype=int32)

In [52]:
arr2[3:]

array([27, 12, 99, 67, 71, 19, 66], dtype=int32)

In [53]:
arr2

array([ 7, 39, 42, 27, 12, 99, 67, 71, 19, 66], dtype=int32)

In [54]:
arr2[2:8]

array([42, 27, 12, 99, 67, 71], dtype=int32)

In [55]:
arr2[6:1:-1]

array([67, 99, 12, 27, 42], dtype=int32)

In [56]:
# arr1[3]
# arr1[2,2]
# arr1[2:4]
# arr1[3:]
# arr1[3,4]
# arr1[2,1:4]
# arr1[3,0:4]
# arr1[2:4,2]

In [57]:
arr1

array([[22,  8, 31, 13, 34],
       [17, 37,  8, 21, 17],
       [27, 19, 22, 30,  9],
       [26,  3, 40, 32,  4],
       [19, 19,  6, 44, 19]], dtype=int32)

In [58]:
arr1[2:3,3:4]

array([[30]], dtype=int32)

In [59]:
arr1[:,4]

array([34, 17,  9,  4, 19], dtype=int32)

In [60]:
arr1[:2,4]

array([34, 17], dtype=int32)

In [61]:
arr1[:,:]

array([[22,  8, 31, 13, 34],
       [17, 37,  8, 21, 17],
       [27, 19, 22, 30,  9],
       [26,  3, 40, 32,  4],
       [19, 19,  6, 44, 19]], dtype=int32)

## Conditional Selection

In [62]:
arr2

array([ 7, 39, 42, 27, 12, 99, 67, 71, 19, 66], dtype=int32)

In [63]:
arr2[arr2%2==0]

array([42, 12, 66], dtype=int32)

In [64]:
arr2[arr2<50]

array([ 7, 39, 42, 27, 12, 19], dtype=int32)

In [65]:
arr2[(arr2>50) & (arr2%2==0)]

array([66], dtype=int32)

In [66]:
arr2

array([ 7, 39, 42, 27, 12, 99, 67, 71, 19, 66], dtype=int32)

In [67]:
arr3=np.where(arr2%2==0,2,-1)

In [68]:
arr3

array([-1, -1,  2, -1,  2, -1, -1, -1, -1,  2])

In [69]:
arr2

array([ 7, 39, 42, 27, 12, 99, 67, 71, 19, 66], dtype=int32)

In [70]:
arr2.sort()

In [71]:
arr2

array([ 7, 12, 19, 27, 39, 42, 66, 67, 71, 99], dtype=int32)

In [72]:
arr1

array([[22,  8, 31, 13, 34],
       [17, 37,  8, 21, 17],
       [27, 19, 22, 30,  9],
       [26,  3, 40, 32,  4],
       [19, 19,  6, 44, 19]], dtype=int32)

In [73]:
arr1.sort()

In [74]:
arr1

array([[ 8, 13, 22, 31, 34],
       [ 8, 17, 17, 21, 37],
       [ 9, 19, 22, 27, 30],
       [ 3,  4, 26, 32, 40],
       [ 6, 19, 19, 19, 44]], dtype=int32)

In [75]:
arr2

array([ 7, 12, 19, 27, 39, 42, 66, 67, 71, 99], dtype=int32)

In [76]:
arr2.sort()

In [77]:
arr2

array([ 7, 12, 19, 27, 39, 42, 66, 67, 71, 99], dtype=int32)

In [78]:
np.where(arr2%2!=0,0,arr2)

array([ 0, 12,  0,  0,  0, 42, 66,  0,  0,  0], dtype=int32)