In [1]:
import numpy as np
import pandas as pd

## 1. Create a NumPy array containing integers from 0 to 9.

In [2]:
data=np.arange(0,10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [3]:
l1=[10,20,30,40,50]
data1=np.array(l1)
data1

array([10, 20, 30, 40, 50])

## 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [4]:
data2=np.arange(9).reshape(3,3)
data2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [5]:
arr4 = np.random.randint(1, 101, size=(5, 4))
print(arr4)

print("Shape:", arr4.shape)
print("Size:", arr4.size)

[[83 43 82 21]
 [ 5 30 32 53]
 [38 15  3 84]
 [50 57 72 27]
 [92  1 33 38]]
Shape: (5, 4)
Size: 20


## 5. Create a 3x3 array of integers and access:
### a. The second element of the first row.
### b. The third column of the 2nd row.
### c. A subarray with the first two rows and last two columns.

In [6]:
arr5=np.arange(9).reshape(3,3)
arr5
a=arr5[0][1]
print("The second element of the first row:",a)
b=arr5[1][2]
print("The third column of the 2nd row:",b)
c=arr5[:2,1:]
print("A subarray with the first two rows and last two columns:")
print(c)

The second element of the first row: 1
The third column of the 2nd row: 5
A subarray with the first two rows and last two columns:
[[1 2]
 [4 5]]


## 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [7]:
arr6=np.arange(1,13)
arr6
arr6=arr6.reshape(3,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 7. Reshape a 3x3 matrix into a 1D array.

In [8]:
arr7=np.arange(1,10).reshape(3,3)
arr7=arr7.flatten()
arr7

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,subtraction, multiplication, and division on them.

In [9]:
x=np.arange(1,7).reshape(2,3)
y=np.arange(7,13).reshape(2,3)
print(x)
print(y)
print('Addition is:')
a=x+y
print(np.array(a))
print('Subtraction is:')
b=y-x
print(np.array(b))
print('multiplication is:')
c=x*y
print(np.array(c))
print('Division is:')
d=y/x
print(np.array(d))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
Addition is:
[[ 8 10 12]
 [14 16 18]]
Subtraction is:
[[6 6 6]
 [6 6 6]]
multiplication is:
[[ 7 16 27]
 [40 55 72]]
Division is:
[[7.  4.  3. ]
 [2.5 2.2 2. ]]


## 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [10]:
arr9=np.arange(1,10)
print("Sum:", np.sum(arr9))
print("Mean:", np.mean(arr9))
print("Standard Deviation:", np.std(arr9))

Sum: 45
Mean: 5.0
Standard Deviation: 2.581988897471611


## 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

In [11]:
A=np.arange(1,5).reshape(2,2)
B=np.arange(5,9).reshape(2,2)
result=np.dot(A,B)
result

#res= A @ B
#res

array([[19, 22],
       [43, 50]])

## 11. Find the transpose of matrix A and matrix B.

In [12]:
A=np.arange(1,5).reshape(2,2)
print(A)
B=np.arange(5,9).reshape(2,2)
print(B)
print("Transpose of A:\n", A.T)
print("Transpose of B:\n", B.T)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Transpose of A:
 [[1 3]
 [2 4]]
Transpose of B:
 [[5 7]
 [6 8]]


## 12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [13]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

arr1d = np.array([10, 20, 30])

result = arr2d + arr1d
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


## 13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [14]:
a=np.arange(1,17).reshape(4,4)
a
print('Maximum  element:',a.max())
print('Minimum  element:',a.min())
print('Average:',a.mean())


Maximum  element: 16
Minimum  element: 1
Average: 8.5


## 14. Find the row-wise and column-wise sums.

In [15]:
print("Row-wise sum:", np.sum(a, axis=1))
print("Column-wise sum:", np.sum(a, axis=0))

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


## 15. Generate an array of 10 random integers between 1 and 50.


In [18]:
arr15=np.random.randint(1,50,10)
arr15

array([11, 40, 46, 27, 28, 20, 23, 49,  7, 32], dtype=int32)

## 16. Generate a 5x5 matrix of random floats between 0 and 1.

In [20]:
arr16 = np.random.rand(5, 5)
print(arr16)

[[0.06515026 0.53159177 0.93312916 0.78820803 0.0718066 ]
 [0.25098457 0.31503615 0.30115025 0.9354598  0.39776845]
 [0.6462694  0.05156349 0.07832515 0.5646212  0.23037039]
 [0.08254708 0.2997532  0.60176593 0.2571117  0.03003635]
 [0.37683499 0.66137046 0.08670043 0.94953461 0.97884999]]
